# Generated by Django 2.0.2 on 2018-02-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20180224_0755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['sort', 'pub_date', 'title']},
        ),
        migrations.AddField(
            model_name='page',
            name='path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
