# Generated by Django 2.0.2 on 2018-02-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20180224_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='path',
            field=models.CharField(blank=True, editable=False, max_length=500, null=True),
        ),
    ]
