# Generated by Django 2.0.2 on 2018-02-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20180224_1154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['dir_path', 'sort', 'pub_date', 'title']},
        ),
        migrations.AddField(
            model_name='page',
            name='dir_path',
            field=models.CharField(blank=True, editable=False, max_length=500, null=True),
        ),
    ]
