# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-27 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20180226_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='body',
            field=models.TextField(max_length=10000000),
        ),
    ]
